integrate with mayhem
mayhemheroes/sndfilter pull request #1
Opened 2022-05-17 17:36 UTC by jbgreenh

2022-06-06 21:55 UTC, xansec requested changes
We have changed support for corpora under `tests` to corpora under `testsuite`. Please change the name of this folder.

2022-06-06 21:55 UTC, xansec commented on Mayhemfile
> +    - cmd: /sndfilter @@ <reverb> <5> <longreverb1>
We do not currently support multiple commands in the Mayhemfile at the moment. Please either omit the extra commands, or split this Mayhemfile into multiple Mayhemfiles (see here: https://community.forallsecure.com/t/error-the-mayhem-for-code-scan-detected-the-mayhem-run-for-your-target-was-unsuccessful-and-multiple-docker-files-in-the-repository/350/5).

2022-06-07 03:45 UTC, jbgreenh commented
updated

2022-06-07 14:33 UTC, xansec commented
LGTM!

2022-06-07 14:33 UTC, xansec commented
LGTM!

2022-06-07 14:33 UTC, merged